[package]
name = "systemon"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term = "0.12.1"
clap = { version = "4.5.18", features = ["derive"] }
serde = "1.0.210"
serde_json = "1.0.128"
sysinfo = "0.31.4"